name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GetStream/android-ci-actions/actions/setup-java@main
      - uses: GetStream/android-ci-actions/actions/gradle-cache@main
        with:
          cache-name: gradle-build
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build